apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    app: myapp
spec:
  type: NodePort
  selector:
    app: myapp
    slot: green
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30020
      protocol: TCP
